### ISSUE TITLE
How does WebAuthn design/architecture influence this design/architecture?

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#18]
Detail the limitations based on Signify.
How do you deal with not having an app like one-password (no desktop app to download ?
If you can't open a popup then can we use the side-panel?

For instance @rodolfomiranda demonstrated the webauthn w/ one password extension:
<img width="680" alt="image" src="https://github.com/WebOfTrust/signify-browser-extension/assets/681493/f963a29a-b07a-4991-b8d1-bee8409d2885">

<img width="676" alt="image" src="https://github.com/WebOfTrust/signify-browser-extension/assets/681493/eefc40df-c3ba-46f0-a2a9-8bbeae7aea66">

<img width="638" alt="image" src="https://github.com/WebOfTrust/signify-browser-extension/assets/681493/4c3fc969-a946-46bd-8f67-055a2f2d67c0">

**Comment by rodolfomiranda** [comment]
<img width="1418" alt="Captura de pantalla 2023-12-12 a la(s) 4 27 23 p m" src="https://github.com/WebOfTrust/signify-browser-extension/assets/2913773/3d9e39ff-6911-4dab-b844-cb65709d00b2">

Adding this screenshot to show how 1password extension ask the user (in spanish in my browser) to "Select the 1Password icon in your browser's tool bar to unlock"

**Comment by rodolfomiranda** [comment]
Some comments regarding the webauthn demo  and how can it be adapted for our browser extension:

- when the extension detects that a webpage requires authentication, it displays a dialog box with one of these options:
  - asking the user to use a saved login (AID-webpage association for example)
  - asking the user to create a new login (save a new AID-webpage association)
  - asking the user to unlock (enter the passcode)

In the first option, if the user accepts, the extension can continue with the flow silently. However, for the second and third options it is necessary that the user interacts with some UI components from the extension. Using a component inside the webpage is not an option since it can be sniffed by the webpage. 
There are two UI components allowed in the extension, a popup and a side-panel. The popup looks better but it can only be opened by the user by clicking on the toolbar icon. Since it can't be opened programmatically, the extension should show an alert to request that action explicitly. On the other hand, the side panel can be opened programmatically, but the user experience is not as good as the popup because it shrinks the webpage window.

**Comment by 2byrds** [comment]
I believe we are ready to wrap this issue up per our conversation with Daniel, and should create new issues regarding the current path forward @rodolfomiranda

**Comment by rodolfomiranda** [comment]
We decided to go with the popup, and ask the user to click on the toolbar icon when necessary.
