### ISSUE TITLE
[Bug] When you use `https` in the URLs you get a weird "failed to fetch" error in the extension and the web worker.

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/signify-browser-extension#215]
# To Reproduce
1. Load clean extension from a build from main
2. Use `https://localhost:3901` `https://localhost:3903` in the boot and agent URL boxes as instructed (also `https://127.0.0.1:3901` and `https://127.0.0.1:3903` work as localhost isn't supported by the extension but somehow the loopback IP is???)
3. Get the weird errors below.

## Input to URLs
![image](https://github.com/user-attachments/assets/dc0d1c36-64c6-435b-82ba-26c57f81ce5b)

## Stack trace in extension
![image](https://github.com/user-attachments/assets/a7b60cb9-c611-4206-9b4e-850d5e2208c2)

## Console output of web worker
```
Background script loaded
index.ts-dc7dd268.js:53 Signify Browser Extension installed
index.ts-dc7dd268.js:53 Message received from browser extension:  ui--authentication-check-agent-connection
index.ts-dc7dd268.js:53 Signify client is not connected undefined
index.ts-dc7dd268.js:53 Message received from browser extension:  ui--authentication-generate-passcode
index.ts-dc7dd268.js:53 Message received from browser extension:  ui--authentication-boot-connect-agent
index.ts-dc7dd268.js:53 TypeError: Failed to fetch
    at Gu.boot (index.ts-dc7dd268.js:53:23720)
    at Object._ [as bootAndConnect] (index.ts-dc7dd268.js:53:30879)
    at async KS (index.ts-dc7dd268.js:53:40417)
_ @ index.ts-dc7dd268.js:53Understand this errorAI
index.ts-dc7dd268.js:53 Message received from browser extension:  ui--authentication-check-agent-connection
index.ts-dc7dd268.js:53 Signify client is not connected null
```

# To Resolve 
1. An appropriate error should be displayed on the client and a proper console log output for errors in the extension and web worker.

# build env
Chrome: Version 130.0.6723.92 (Official Build) (64-bit)
Build Extension from main commit: 2799a162ae1b93bc54c284f1833aa4077e58e876

**Comment by HunnySajid** [comment]
@daidoji thank you for reporting this.
I am wondering how `https` is supposed to work with localhost.
Have you created a local secure tunnel so that `localhost` can be accessed with `https`? 
Are you able to visit https://localhost:3903/health in your browser?
In my case, I can access http://localhost:3903/health in my browser and following agent_url and boot_url work for me in browser extension:
agent_url: http://localhost:3901 OR http://127.0.0.1:3901
boot_url: http://localhost:3903 OR http://127.0.0.1:3903

But `https` scheme does not work and that is expected as we might need to setup certificates for that I assume.

Thoughts?

**Comment by daidoji** [comment]
Sorry, we used https unwittingly because we assumed keria would at least use self-signed tls as a baseline security measure.  

This bug's intention though wasn't necessarily used to get https to be enabled for the extension, but rather for the extension to throw a better error message or dialogue on URLs that aren't working properly.  "Failed to fetch and a strange stack trace in the error logs" don't seem like a great combination for the end user.

**Comment by HunnySajid** [comment]
> Sorry, we used https unwittingly because we assumed keria would at least use self-signed tls as a baseline security measure.
> 
> This bug's intention though wasn't necessarily used to get https to be enabled for the extension, but rather for the extension to throw a better error message or dialogue on URLs that aren't working properly. "Failed to fetch and a strange stack trace in the error logs" don't seem like a great combination for the end user.

Thank you for the details. I agree that "Failed to fetch" error can be replaced with a more user friendly statement. But this is thrown natively by browser when fetch request fails (could be due to several reasons)

<img width="830" alt="Screenshot 2024-11-12 at 7 50 58 PM" src="https://github.com/user-attachments/assets/ad0e314d-ac22-45f5-9111-3aef3c04f126">

Perhaps, we can implement a custom handler for that case. But I got the point that it is related to "Failed to fetch" rather an https problem.
Thanks
